---
title: "An Analysis of a Survey on Masculinity"
author: "Natascha Otto"
date: "1 11 2019"
output: html_document
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
#In this chunk I selected and cleaned up certain variables from the raw data set
#and proceeded to create a new data frame to work with.

library(dplyr)
raw_data <- readr::read_csv(file = "data/raw_responses.csv")
library(tidyr)
library(forcats)

data <- raw_data %>%
  select(q0002, q0021_0001, q0021_0002, q0021_0003, q0021_0004, q0024, age3) %>%
  rename(
    mascImportance = q0002, 
    sexBoundaries_tooFar = q0021_0001, 
    sexBoundaries_talkFriend = q0021_0002, 
    sexBoundaries_talkEx = q0021_0003, 
    sexBoundaries_none = q0021_0004, 
    marriageStatus = q0024, 
    age = age3
  ) %>% 
  mutate(
    sexBoundaries_tooFar = sexBoundaries_tooFar != "Not selected",
    sexBoundaries_talkFriend = sexBoundaries_talkFriend != "Not selected",
    sexBoundaries_talkEx = sexBoundaries_talkEx != "Not selected",
    sexBoundaries_none = sexBoundaries_none != "Not selected",
  ) %>%
  mutate(
    mascImportance = ordered(
      x = mascImportance, 
      levels = c("Very important", "Somewhat important", "Not too important", "Not at all important", "No answer")
    ),
    age = ordered(
      x = age,
      levels = c("18 - 34", "35 - 64", "65 and up")
    )
  )

data

```

# The importance of being seen as masculine

```{r, message=FALSE, warning=FALSE}
#This chunk conveys how important it is to men to be seen as masculine in form 
#of a bar chart.

## Plot
library(ggplot2)
a <- ggplot(
  data = data, 
  mapping = aes(x = mascImportance, fill = mascImportance,
                show.legend = FALSE)
) + geom_bar(alpha = 0.5) + 
  labs(
  title = "The importance of being seen as masculine", 
  x = "Importance of being seen as masculine", 
  y = "Count", 
  fill = "Importance of being seen as masculine") + 
  theme(legend.position = "none")
print(a) #had to use print function bc RStudio didn't print plot automatically 

```

# The correlation between age and the importance of being seen as masculine

```{r}
#This chunk depicts the correlation between age and the importance of being 
#seen as masculine via a crosstable and a plot.

## Crosstable 
importanceAge <- with (data, table(age, mascImportance))
(importanceAge <- round(addmargins(prop.table(importanceAge)*100), 2))

##  Plot
library(ggplot2)
b <- ggplot(
  data = data,
  mapping = aes(x = age, y = mascImportance, colour = mascImportance)
) + geom_count(alpha = 0.5) + 
  labs(
    title = "Age and the importance of being seen as masculine",
    subtitle = "This part depicts the correlation between age and the importance of being seen as masculine",
    x = "Age",
    y = "Importance of being seen as masculine",
    colour = "Importance of being seen as masculine"
  )
print(b)

```


## How sexual boundaries were gauged in the last 12 months 
### This part shows how men estimated whether they pushed a partner too far in a past sexual encounter

```{r}
#This chunk deals with the question how the interviewed men gauged sexual boundaries
#in the last 12 months. To guarantee an easier work flow and because the question 
#was designed to have the option of multiple choice answers and was therefore depicted
#with a variable for each question, I decided to select the relevant variables and
#combine them in a smaller data frame dedicaded to the topic of sexual boundaries. 
#Later on I also decided to recode each variable into factors for nicer plots.


library(dplyr)
library(tidyr)
sexBoundaries <- raw_data %>%
  select(q0021_0001, q0021_0002, q0021_0003, q0021_0004) %>%
  rename(
    sexBoundaries_tooFar = q0021_0001, 
    sexBoundaries_talkFriend = q0021_0002, 
    sexBoundaries_talkEx = q0021_0003, 
    sexBoundaries_none = q0021_0004) 

sexBoundaries$sexBoundaries_tooFar <- factor(sexBoundaries$sexBoundaries_tooFar, levels = c("Wondered whether you pushed a partner too far in a past sexual encounter.", "Not selected"), labels = c("Yes", "No")) 

sexBoundaries$sexBoundaries_talkFriend <- factor(sexBoundaries$sexBoundaries_talkFriend, levels = c("Talked with a friend or friends about whether you pushed a partner too far.", "Not selected"), labels = c("Yes", "No"))

sexBoundaries$sexBoundaries_talkEx <- factor(sexBoundaries$sexBoundaries_talkEx, levels = c("Contacted a past sexual partner to ask whether you went too far in any of you sexual encounters.","Not selected"), labels = c("Yes", "No"))

sexBoundaries$sexBoundaries_none <- factor(sexBoundaries$sexBoundaries_none, levels = c("None of the above", "Not selected"), labels = c("Yes", "No"))

```



```{r}
library(ggplot2)

c <- ggplot(data = sexBoundaries,
            mapping = aes(sexBoundaries_tooFar, fill = sexBoundaries_tooFar, show.legend = FALSE)
) + geom_bar(alpha = 0.5) +
  labs(
    title = "1. Wondered whether they pushed a partner too far",
    x = "Wondered whether they pushed a partner too far",
    y = "Count",
    fill = "Wondered whether they pushed a partner too far"
  ) + 
  theme(legend.position = "none")
print(c)

#might remove tags on the side bc they take up too much space & are unneccessary

```



```{r}
library(ggplot2)

d <- ggplot(data = sexBoundaries,
            mapping = aes(sexBoundaries_talkFriend, fill = sexBoundaries_talkFriend, show.legend = FALSE)
) + geom_bar(alpha = 0.5) +
  labs(
    title = "2. Talked to friends about whether they pushed a partner too far",
    x = "Talked to friends about whether they pushed a partner too far",
    y = "Count",
    fill = "Talked to friends about whether they pushed a partner too far"
  ) +
  theme(legend.position = "none")
print(d)
```



```{r}
library(ggplot2)

e <- ggplot(data = sexBoundaries,
            mapping = aes(sexBoundaries_talkEx, fill = sexBoundaries_talkEx, show.legend = FALSE)
) + geom_bar(alpha = 0.5) +
  labs(
    title = "3. Talked to an Ex about whether they pushed a partner too far",
    x = "Talked to an Ex about whether they pushed a partner too far",
    y = "Count",
    fill = "Talked to an Ex about whether they pushed a partner too far"
  ) + 
  theme(legend.position = "none")
print(e)
```



```{r}
library(ggplot2)

f <- ggplot(data = sexBoundaries, 
            mapping = aes(sexBoundaries_none, fill = sexBoundaries_none, show.legend = FALSE)
) + geom_bar(alpha = 0.5) +
  labs(
    title = "4. Didn't do any of the above",
    x = "Didn't do any of the above",
    y = "Count",
    fill = "Didn't do any of the above"
  ) + 
  theme(legend.position = "none")
print(f)
```

